In [1]:
# Write a NumPy program to implement following operation 
# to convert a list of numeric values into a one-dimensional NumPy array

# Hitarth M Hindocha
# 216270307045

####################################################################################
import numpy as np
a=[1,2,3,4,5] # created list
print("List is : ",a)
b=np.array(a) # converted into array
print("Array is : ",b)

####################################################################################




List is :  [1, 2, 3, 4, 5]
Array is :  [1 2 3 4 5]


In [2]:

# to create a 3x3 matrix with values ranging from 2 to 10

# Hitarth M Hindocha
# 216270307045

import numpy as np
a=np.arange(2,11).reshape(3,3)
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
# to append values at the end of an array

# Hitarth M Hindocha
# 216270307045
