In [1]:
import numpy as np

arr=np.array([[1,2,3],[4,5,6]])
print("Original Array is : ")
print(arr)
print()

print("Flattened Array is : ")
farr=arr.flatten()
print(farr)
print()

max=farr.max()
print("Maximum is : ",max)

min=farr.min()
print("Minimum is : ",min)

Original Array is : 
[[1 2 3]
 [4 5 6]]

Flattened Array is : 
[1 2 3 4 5 6]

Maximum is :  6
Minimum is :  1


In [2]:
import numpy as np

arr=np.arange(1,10)
print(arr)
print()

mean=arr.mean()
print(mean)
std=arr.std()
print("Standard Deviation : ",std)
var=arr.var()
print("Variance : ",var)


[1 2 3 4 5 6 7 8 9]

5.0
Standard Deviation :  2.581988897471611
Variance :  6.666666666666667
