In [1]:
# Write a NumPy program to implement following operation 
# to convert a list of numeric values into a one-dimensional NumPy array

# Hitarth M Hindocha
# 216270307045

####################################################################################
import numpy as np
a=[1,2,3,4,5] # created list
print("List is : ",a)
b=np.array(a) # converted into array
print("Array is : ",b)

####################################################################################




List is :  [1, 2, 3, 4, 5]
Array is :  [1 2 3 4 5]


In [2]:

# to create a 3x3 matrix with values ranging from 2 to 10

# Hitarth M Hindocha
# 216270307045


####################################################################################

import numpy as np
a=np.arange(2,11).reshape(3,3)
print(a)


####################################################################################


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
# to create another shape from an array without changing its data(3*2 to 2*3)

# Hitarth M Hindocha
# 216270307045


####################################################################################

import numpy as np

arr=np.array([1,2,3,4,5,6])
print("Original Array : ",arr)
print()
print("Array of 3 row 2 column is  ")
print()
x=np.reshape(arr,(3,2))
print(x)
print()
print("Array of 2 row 3 column is  ")
print()
y=np.reshape(arr,(2,3))
print(y)

####################################################################################


Original Array :  [1 2 3 4 5 6]

Array of 3 row 2 column is  

[[1 2]
 [3 4]
 [5 6]]

Array of 2 row 3 column is  

[[1 2 3]
 [4 5 6]]
